#!/usr/bin/env python3

G1D_NUM_MOTOR = 29

WAIST_YAW = 12
WAIST_PITCH = 14

LEFT_SHOULDER_PITCH = 15
LEFT_SHOULDER_ROLL = 16
LEFT_SHOULDER_YAW = 17
LEFT_ELBOW = 18
LEFT_WRIST_ROLL = 19
LEFT_WRIST_PITCH = 20
LEFT_WRIST_YAW = 21

RIGHT_SHOULDER_PITCH = 22
RIGHT_SHOULDER_ROLL = 23
RIGHT_SHOULDER_YAW = 24
RIGHT_ELBOW = 25
RIGHT_WRIST_ROLL = 26
RIGHT_WRIST_PITCH = 27
RIGHT_WRIST_YAW = 28

LEFT_ARM_LOW_LEVEL = [
    LEFT_SHOULDER_PITCH,
    LEFT_SHOULDER_ROLL,
    LEFT_SHOULDER_YAW,
    LEFT_ELBOW,
    LEFT_WRIST_ROLL,
    LEFT_WRIST_PITCH,
    LEFT_WRIST_YAW,
]

RIGHT_ARM_LOW_LEVEL = [
    RIGHT_SHOULDER_PITCH,
    RIGHT_SHOULDER_ROLL,
    RIGHT_SHOULDER_YAW,
    RIGHT_ELBOW,
    RIGHT_WRIST_ROLL,
    RIGHT_WRIST_PITCH,
    RIGHT_WRIST_YAW,
]
