#!/usr/bin/env python3

from robot.model.joint_indices import (
    WAIST_YAW,
    WAIST_PITCH,
    LEFT_SHOULDER_PITCH,
    LEFT_SHOULDER_ROLL,
    LEFT_SHOULDER_YAW,
    LEFT_ELBOW,
    LEFT_WRIST_ROLL,
    LEFT_WRIST_PITCH,
    LEFT_WRIST_YAW,
    RIGHT_SHOULDER_PITCH,
    RIGHT_SHOULDER_ROLL,
    RIGHT_SHOULDER_YAW,
    RIGHT_ELBOW,
    RIGHT_WRIST_ROLL,
    RIGHT_WRIST_PITCH,
    RIGHT_WRIST_YAW,
)

WAIST = [
    WAIST_YAW,
    WAIST_PITCH,
]

LEFT_ARM = [
    LEFT_SHOULDER_PITCH,
    LEFT_SHOULDER_ROLL,
    LEFT_SHOULDER_YAW,
    LEFT_ELBOW,
    LEFT_WRIST_ROLL,
    LEFT_WRIST_PITCH,
    LEFT_WRIST_YAW,
]

RIGHT_ARM = [
    RIGHT_SHOULDER_PITCH,
    RIGHT_SHOULDER_ROLL,
    RIGHT_SHOULDER_YAW,
    RIGHT_ELBOW,
    RIGHT_WRIST_ROLL,
    RIGHT_WRIST_PITCH,
    RIGHT_WRIST_YAW,
]

ARMS = LEFT_ARM + RIGHT_ARM
UPPER_BODY = WAIST + ARMS
