#!/usr/bin/env python3

G1D_NUM_MOTOR = 29

LEFT_HIP_PITCH = 0
LEFT_HIP_ROLL = 1
LEFT_HIP_YAW = 2
LEFT_KNEE = 3
LEFT_ANKLE_PITCH = 4
LEFT_ANKLE_ROLL = 5

RIGHT_HIP_PITCH = 6
RIGHT_HIP_ROLL = 7
RIGHT_HIP_YAW = 8
RIGHT_KNEE = 9
RIGHT_ANKLE_PITCH = 10
RIGHT_ANKLE_ROLL = 11

WAIST_YAW = 12
WAIST_ROLL = 13
WAIST_PITCH = 14

LEFT_SHOULDER_PITCH = 15
LEFT_SHOULDER_ROLL = 16
LEFT_SHOULDER_YAW = 17
LEFT_ELBOW = 18
LEFT_WRIST_ROLL = 19
LEFT_WRIST_PITCH = 20
LEFT_WRIST_YAW = 21

RIGHT_SHOULDER_PITCH = 22
RIGHT_SHOULDER_ROLL = 23
RIGHT_SHOULDER_YAW = 24
RIGHT_ELBOW = 25
RIGHT_WRIST_ROLL = 26
RIGHT_WRIST_PITCH = 27
RIGHT_WRIST_YAW = 28

INVALID_FOR_G1D = [
    LEFT_HIP_PITCH,
    LEFT_HIP_ROLL,
    LEFT_HIP_YAW,
    LEFT_KNEE,
    LEFT_ANKLE_PITCH,
    LEFT_ANKLE_ROLL,
    RIGHT_HIP_PITCH,
    RIGHT_HIP_ROLL,
    RIGHT_HIP_YAW,
    RIGHT_KNEE,
    RIGHT_ANKLE_PITCH,
    RIGHT_ANKLE_ROLL,
    WAIST_ROLL,
]

VALID_FOR_G1D = [
    WAIST_YAW,
    WAIST_PITCH,
    LEFT_SHOULDER_PITCH,
    LEFT_SHOULDER_ROLL,
    LEFT_SHOULDER_YAW,
    LEFT_ELBOW,
    LEFT_WRIST_ROLL,
    LEFT_WRIST_PITCH,
    LEFT_WRIST_YAW,
    RIGHT_SHOULDER_PITCH,
    RIGHT_SHOULDER_ROLL,
    RIGHT_SHOULDER_YAW,
    RIGHT_ELBOW,
    RIGHT_WRIST_ROLL,
    RIGHT_WRIST_PITCH,
    RIGHT_WRIST_YAW,
]

JOINT_INDEX_TO_NAME = {
    WAIST_YAW: "waist_yaw",
    WAIST_PITCH: "waist_pitch",
    LEFT_SHOULDER_PITCH: "left_shoulder_pitch",
    LEFT_SHOULDER_ROLL: "left_shoulder_roll",
    LEFT_SHOULDER_YAW: "left_shoulder_yaw",
    LEFT_ELBOW: "left_elbow",
    LEFT_WRIST_ROLL: "left_wrist_roll",
    LEFT_WRIST_PITCH: "left_wrist_pitch",
    LEFT_WRIST_YAW: "left_wrist_yaw",
    RIGHT_SHOULDER_PITCH: "right_shoulder_pitch",
    RIGHT_SHOULDER_ROLL: "right_shoulder_roll",
    RIGHT_SHOULDER_YAW: "right_shoulder_yaw",
    RIGHT_ELBOW: "right_elbow",
    RIGHT_WRIST_ROLL: "right_wrist_roll",
    RIGHT_WRIST_PITCH: "right_wrist_pitch",
    RIGHT_WRIST_YAW: "right_wrist_yaw",
}

JOINT_NAME_TO_INDEX = {name: index for index, name in JOINT_INDEX_TO_NAME.items()}
